apiVersion: v1
appVersion: "1.0"
description: Config for records-of-processing-activities etl
name: records-of-processing-activities-etl
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/records-of-processing-activities-etl