name: Build and deploy on push to branch

on:
  push:
    branches:
      - no

jobs:
  build-and-deploy:
    name: Deploy to prod environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Setup python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup gcloud CLI
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

    - run: gcloud auth configure-docker eu.gcr.io

    - name: Build Docker image with GitHub commit sha tag and staging tag
      run: docker build . -t eu.gcr.io/digdir-fdk-infra/records-of-processing-activities-etl:latest -t eu.gcr.io/digdir-fdk-infra/records-of-processing-activities-etl:$GITHUB_SHA

    - name: Publish docker image to Google Cloud
      run: docker -- push eu.gcr.io/digdir-fdk-infra/records-of-processing-activities-etl -a

    - name: Apply Helm template
      run: |
        helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/records-of-processing-activities-etl:$GITHUB_SHA" -f ./helm-sources/values/prod.yaml ./helm-sources/  > ./kubectlapply.yaml
        chmod o+w ./kubectlapply.yaml
        cat kubectlapply.yaml

    - name: Setup gcloud CLI for deploy
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}

    - name: Deploy to GCP
      run: |
        gcloud container clusters get-credentials digdir-fdk-prod --region europe-north1-a --project digdir-fdk-prod
        kubectl apply -f ./kubectlapply.yaml --force
